# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Proyecto', models.IntegerField()),
                ('ID_usuario', models.IntegerField()),
                ('Categoria', models.CharField(choices=[('horror', 'Horror'), ('comedy', 'Comedy'), ('action', 'Action'), ('drama', 'Drama')], max_length=10)),
                ('Subcategoria', models.CharField(choices=[('horror', 'Horror'), ('comedy', 'Comedy'), ('action', 'Action'), ('drama', 'Drama')], max_length=10)),
                ('Monto_pedido', models.FloatField()),
                ('Monto_aprobado', models.FloatField()),
                ('Monto_recaudado', models.FloatField()),
                ('Plazo_dias', models.IntegerField()),
                ('Tasa_de_interes', models.CharField(max_length=100)),
                ('Fecha_inicio', models.DateField()),
                ('Fecha_termino', models.DateField()),
                ('Cuota', models.FloatField()),
                ('Comision', models.FloatField()),
            ],
        ),
    ]
