# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0002_userdonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Proyecto', models.IntegerField()),
                ('ID_usuario', models.IntegerField()),
                ('Monto_recaudado', models.FloatField()),
                ('Fecha', models.DateField()),
            ],
        ),
    ]
