# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0003_fundingdonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Proyecto', models.IntegerField()),
                ('ID_Usuario', models.IntegerField()),
                ('Categoria', models.CharField(choices=[('horror', 'Horror'), ('comedy', 'Comedy'), ('action', 'Action'), ('drama', 'Drama')], max_length=10)),
                ('Subcategoria', models.CharField(choices=[('horror', 'Horror'), ('comedy', 'Comedy'), ('action', 'Action'), ('drama', 'Drama')], max_length=10)),
                ('Plazo_Dias', models.IntegerField()),
                ('Fecha_Inicio', models.DateField()),
                ('Fecha_Termino', models.DateField()),
                ('Monto_Recaudado', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ProyectDonation',
        ),
        migrations.RenameField(
            model_name='fundingdonation',
            old_name='ID_usuario',
            new_name='ID_Usuario',
        ),
        migrations.RenameField(
            model_name='fundingdonation',
            old_name='Monto_recaudado',
            new_name='Monto_Recaudado',
        ),
    ]
