# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_usuario', models.IntegerField()),
                ('Sexo', models.CharField(choices=[('mujer', 'mujer'), ('hombre', 'hombre')], max_length=10)),
                ('AnioNacimiento', models.DateField()),
                ('Estado', models.CharField(choices=[('B.C.', 'B.C.'), ('B.C.S.', 'B.C.S.'), ('Camp.', 'Camp.'), ('Coah.', 'Coah.'), ('Col.', 'Col.'), ('Chis.', 'Chis.'), ('Chih.', 'Chih.'), ('D.F.', 'D.F.'), ('Dgo.', 'Dgo.'), ('Gto.', 'Gto.')], max_length=10)),
                ('Edad', models.IntegerField()),
            ],
        ),
    ]
