# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0006_fundingcapital_fundingdeuda_projectcapital_projectdeuda_usercapital_userdeuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercapital',
            name='Estado',
            field=models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja_California_Sur', 'Baja_California_Sur'), ('Campeche', 'Campeche'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('Ciudad de M\xe9xico', 'Ciudad de M\xe9xico'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Durango', 'Durango'), ('Estado de M\xe9xico', 'Estado de M\xe9xico'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('Michoac\xe1n', 'Michoac\xe1n'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo Le\xf3n', 'Nuevo Le\xf3n'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Quer\xe9taro', 'Quer\xe9taro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potos\xed', 'San Luis Potos\xed'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucat\xe1n', 'Yucat\xe1n'), ('Zacatecas', 'Zacatecas')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userdeuda',
            name='Estado',
            field=models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja_California_Sur', 'Baja_California_Sur'), ('Campeche', 'Campeche'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('Ciudad de M\xe9xico', 'Ciudad de M\xe9xico'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Durango', 'Durango'), ('Estado de M\xe9xico', 'Estado de M\xe9xico'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('Michoac\xe1n', 'Michoac\xe1n'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo Le\xf3n', 'Nuevo Le\xf3n'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Quer\xe9taro', 'Quer\xe9taro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potos\xed', 'San Luis Potos\xed'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucat\xe1n', 'Yucat\xe1n'), ('Zacatecas', 'Zacatecas')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userdonation',
            name='Estado',
            field=models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja_California_Sur', 'Baja_California_Sur'), ('Campeche', 'Campeche'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('Ciudad de M\xe9xico', 'Ciudad de M\xe9xico'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Durango', 'Durango'), ('Estado de M\xe9xico', 'Estado de M\xe9xico'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('Michoac\xe1n', 'Michoac\xe1n'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo Le\xf3n', 'Nuevo Le\xf3n'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Quer\xe9taro', 'Quer\xe9taro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potos\xed', 'San Luis Potos\xed'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucat\xe1n', 'Yucat\xe1n'), ('Zacatecas', 'Zacatecas')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userrecompensas',
            name='Estado',
            field=models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja_California_Sur', 'Baja_California_Sur'), ('Campeche', 'Campeche'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('Ciudad de M\xe9xico', 'Ciudad de M\xe9xico'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Durango', 'Durango'), ('Estado de M\xe9xico', 'Estado de M\xe9xico'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('Michoac\xe1n', 'Michoac\xe1n'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo Le\xf3n', 'Nuevo Le\xf3n'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Quer\xe9taro', 'Quer\xe9taro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potos\xed', 'San Luis Potos\xed'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucat\xe1n', 'Yucat\xe1n'), ('Zacatecas', 'Zacatecas')], max_length=10),
        ),
    ]
