# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0010_auto_20170818_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundingcapital',
            old_name='ID_Proyecto',
            new_name='IdProyecto',
        ),
        migrations.RenameField(
            model_name='fundingcapital',
            old_name='ID_Usuario',
            new_name='IdUsuario',
        ),
        migrations.RenameField(
            model_name='fundingcapital',
            old_name='Monto_Recaudado',
            new_name='MontoRecaudado',
        ),
        migrations.RenameField(
            model_name='fundingdeuda',
            old_name='ID_Proyecto',
            new_name='IdProyecto',
        ),
        migrations.RenameField(
            model_name='fundingdeuda',
            old_name='ID_Usuario',
            new_name='IdUsuario',
        ),
        migrations.RenameField(
            model_name='fundingdeuda',
            old_name='Monto_Recaudado',
            new_name='MontoRecaudado',
        ),
        migrations.RenameField(
            model_name='fundingdonation',
            old_name='ID_Proyecto',
            new_name='IdProyecto',
        ),
        migrations.RenameField(
            model_name='fundingdonation',
            old_name='ID_Usuario',
            new_name='IdUsuario',
        ),
        migrations.RenameField(
            model_name='fundingdonation',
            old_name='Monto_Recaudado',
            new_name='MontoRecaudado',
        ),
        migrations.RenameField(
            model_name='fundingrecompensas',
            old_name='Exito_Fondeo',
            new_name='ExitoFondeo',
        ),
        migrations.RenameField(
            model_name='fundingrecompensas',
            old_name='ID_Proyecto',
            new_name='IdProyecto',
        ),
        migrations.RenameField(
            model_name='fundingrecompensas',
            old_name='ID_Usuario',
            new_name='IdUsuario',
        ),
        migrations.RenameField(
            model_name='fundingrecompensas',
            old_name='Monto_Recaudado',
            new_name='MontoRecaudado',
        ),
        migrations.RemoveField(
            model_name='fundingdeuda',
            name='Tipo_Movimiento',
        ),
        migrations.AddField(
            model_name='fundingcapital',
            name='ExitoFondeo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundingcapital',
            name='Fondeadores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundingdeuda',
            name='ExitoFondeo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundingdeuda',
            name='Fondeadores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundingdonation',
            name='ExitoFondeo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundingdonation',
            name='Fondeadores',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
