# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0012_auto_20170818_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcapital',
            old_name='Cuota_Comision',
            new_name='CuotaComision',
        ),
        migrations.RenameField(
            model_name='projectcapital',
            old_name='Fecha_Inicio',
            new_name='FechaInicio',
        ),
        migrations.RenameField(
            model_name='projectcapital',
            old_name='Fecha_Termino',
            new_name='FechaTermino',
        ),
        migrations.RenameField(
            model_name='projectcapital',
            old_name='ID_Proyecto',
            new_name='IdProyecto',
        ),
        migrations.RenameField(
            model_name='projectcapital',
            old_name='ID_Usuario',
            new_name='IdUsuario',
        ),
        migrations.RenameField(
            model_name='projectcapital',
            old_name='Monto_Aprobado',
            new_name='MontoPedido',
        ),
        migrations.RenameField(
            model_name='projectcapital',
            old_name='Monto_Recaudado',
            new_name='MontoRecaudado',
        ),
        migrations.RenameField(
            model_name='projectcapital',
            old_name='Plazo_Dias',
            new_name='PlazoDias',
        ),
        migrations.RenameField(
            model_name='projectcapital',
            old_name='Tasa_Interes',
            new_name='TasaInteresAnual',
        ),
        migrations.RenameField(
            model_name='projectdeuda',
            old_name='Capital_Pagado',
            new_name='CuotaComision',
        ),
        migrations.RenameField(
            model_name='projectdeuda',
            old_name='Fecha_Inicio',
            new_name='FechaInicio',
        ),
        migrations.RenameField(
            model_name='projectdeuda',
            old_name='Fecha_Termino',
            new_name='FechaTermino',
        ),
        migrations.RenameField(
            model_name='projectdeuda',
            old_name='ID_Proyecto',
            new_name='IdProyecto',
        ),
        migrations.RenameField(
            model_name='projectdeuda',
            old_name='ID_Usuario',
            new_name='IdUsuario',
        ),
        migrations.RenameField(
            model_name='projectdeuda',
            old_name='Monto_Aprobado',
            new_name='MontoPedido',
        ),
        migrations.RenameField(
            model_name='projectdeuda',
            old_name='Plazo_Dias',
            new_name='PlazoDias',
        ),
        migrations.RenameField(
            model_name='projectdeuda',
            old_name='Comision_Apertura',
            new_name='TasaInteresAnual',
        ),
        migrations.RenameField(
            model_name='projectdonation',
            old_name='Fecha_Inicio',
            new_name='FechaInicio',
        ),
        migrations.RenameField(
            model_name='projectdonation',
            old_name='Fecha_Termino',
            new_name='FechaTermino',
        ),
        migrations.RenameField(
            model_name='projectdonation',
            old_name='ID_Proyecto',
            new_name='IdProyecto',
        ),
        migrations.RenameField(
            model_name='projectdonation',
            old_name='ID_Usuario',
            new_name='IdUsuario',
        ),
        migrations.RenameField(
            model_name='projectdonation',
            old_name='Monto_Recaudado',
            new_name='MontoPedido',
        ),
        migrations.RenameField(
            model_name='projectdonation',
            old_name='Plazo_Dias',
            new_name='PlazoDias',
        ),
        migrations.RenameField(
            model_name='projectrecompesas',
            old_name='Fecha_Inicio',
            new_name='FechaInicio',
        ),
        migrations.RenameField(
            model_name='projectrecompesas',
            old_name='Fecha_Termino',
            new_name='FechaTermino',
        ),
        migrations.RenameField(
            model_name='projectrecompesas',
            old_name='ID_Proyecto',
            new_name='IdProyecto',
        ),
        migrations.RenameField(
            model_name='projectrecompesas',
            old_name='ID_Usuario',
            new_name='IdUsuario',
        ),
        migrations.RenameField(
            model_name='projectrecompesas',
            old_name='Monto_Recaudado',
            new_name='MontoPedido',
        ),
        migrations.RenameField(
            model_name='projectrecompesas',
            old_name='Plazo_Dias',
            new_name='PlazoDias',
        ),
        migrations.RemoveField(
            model_name='projectcapital',
            name='Monto_Fondeado',
        ),
        migrations.RemoveField(
            model_name='projectdeuda',
            name='Interes_Moratorios_Pagados',
        ),
        migrations.RemoveField(
            model_name='projectdeuda',
            name='Interes_Pagados',
        ),
        migrations.RemoveField(
            model_name='projectdeuda',
            name='Monto_Fondeado',
        ),
        migrations.RemoveField(
            model_name='projectdeuda',
            name='Tasa_Anual_fraccion',
        ),
        migrations.AddField(
            model_name='projectdeuda',
            name='MontoRecaudado',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectdonation',
            name='CuotaComision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdonation',
            name='MontoRecaudado',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectdonation',
            name='TasaInteresAnual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectrecompesas',
            name='CuotaComision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectrecompesas',
            name='MontoRecaudado',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectrecompesas',
            name='TasaInteresAnual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectcapital',
            name='Categoria',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='projectcapital',
            name='Subcategoria',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='projectdeuda',
            name='Categoria',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='projectdeuda',
            name='Subcategoria',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='projectdonation',
            name='Categoria',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='projectdonation',
            name='Subcategoria',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='projectrecompesas',
            name='Categoria',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='projectrecompesas',
            name='Subcategoria',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
