apiVersion: v1
kind: Service
metadata:
  labels:
    component: api-crowdfunding
  name: api-crowdfunding
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: api-crowdfunding
  type: LoadBalancer
